### ISSUE TITLE
Group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by michael-duke** [michael-duke/Capstone-II#22]
## Kanban board for Gamify

In this milestone we have :
- Used a Kanban board with filled-in tasks that have categories and time estimations to assign work in group.
- Assigned _**Student A**_ : @michael-duke  and _**Student B**_: @aceDavon since we are a group of 2 Micronauts.
- Removed all **_Student C_** tasks and replace them with our own cards like; 
    -  _Add hero section_ 
    -  _Create filter feature_
    - We will add more if we can 😄 
- [Link](https://github.com/michael-duke/Capstone-II/projects/1) to Kanban board

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @michael-duke and @aceDavon,

Good job so far!
✔️ Kanban columns are well set up
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [x] You are yet to assign your tasks to members of the team. Kindly do that.

  ![andre-assigned](https://user-images.githubusercontent.com/36542986/187179085-d49f28db-cd05-4595-bc0f-358077d2eaf6.jpg)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by michael-duke** [comment]
Thank you for your feedback @TedLivist

We have actually assigned Student A and student B like so:
 _**Student A**_ : @michael-duke  and _**Student B**_: @aceDavon

We have assigned cards now as well, kindly find the link [here](https://github.com/michael-duke/Capstone-II/projects/1)
Happy coding :smile: 🚀

**Comment by Bondok6** [comment]
# STATUS: APPROVED :green_circle: :clap: 

## Hi @michael-duke and @aceDavon 🙋‍♂️, 
Your Kanban board is set up correctly!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

<img src="https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966" />


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by michael-duke** [comment]
Thank you @TedLivist and @Bondok6 for your kind feedbacks
Hapyy Coding :smile: 🚀
